# .github/workflows/scheduled-builds.yml
name: Scrape and Update on a CRON Schedule

on:
  schedule:
    # Runs "At minute 0 past every hour."
    - cron: '0 */1 * * *'

jobs:
  runscript:
    name: Scrape and Update Firestore
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_ACC: ${{ secrets.FIREBASE_SERVICE_ACC }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: npm start
